#!/bin/bash

dotfiles="dircolors gitconfig gitignore terminfo tmux.conf Xresources \
  zshenv zshrc"
nodotfiles="zsh-fns"

echo "Deleting previous configuration and creating links..."
for f in $dotfiles; do
  rm -rf ~/.$f
  ln -s $PWD/$f ~/.$f
done
for f in $nodotfiles; do
  rm -rf ~/$f
  ln -s $PWD/$f ~/$f
done
