#!/bin/bash

dotfiles="dircolors gitconfig gitignore repl-help.lisp stylish-haskell.yaml \
  terminfo tmux.conf Xresources xprofile zsh.d zshenv zshrc"
nodotfiles=""

echo "Deleting previous configuration and creating links..."
for f in $dotfiles; do
  rm -rf ~/.$f
  ln -s $PWD/$f ~/.$f
done
for f in $nodotfiles; do
  rm -rf ~/$f
  ln -s $PWD/$f ~/$f
done
